{ name = "httpurple"
, dependencies =
  [ "aff"
  , "arrays"
  , "bifunctors"
  , "console"
  , "control"
  , "debug"
  , "effect"
  , "either"
  , "exceptions"
  , "foldable-traversable"
  , "foreign"
  , "foreign-object"
  , "functions"
  , "js-uri"
  , "justifill"
  , "lists"
  , "literals"
  , "maybe"
  , "newtype"
  , "node-buffer"
  , "node-event-emitter"
  , "node-fs"
  , "node-net"
  , "node-http"
  , "node-process"
  , "node-streams"
  , "options"
  , "ordered-collections"
  , "posix-types"
  , "prelude"
  , "profunctor"
  , "record"
  , "record-studio"
  , "refs"
  , "routing-duplex"
  , "safe-coerce"
  , "strings"
  , "transformers"
  , "tuples"
  , "type-equality"
  , "typelevel-prelude"
  , "unsafe-coerce"
  , "untagged-union"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs" ]
, license = "MIT"
, repository = "https://github.com/sigma-andex/purescript-httpurple.git"
}
